### ISSUE TITLE
Feature to keep colors causes problems in Internet Explorer

### ISSUE THREAD

**Issue by RWeigelt** [MattDiMu/gulp-sassvg#6]
After updating to version 1.5.0 I came across the strange problem, that _some_ icons in our didn't appear in Internet Explorer (11), but showed without problems in Chrome or Firefox.

Turned out that the affected icons where those where I wanted the colors to be unchanged (for 1.4.2 I saved these icons in Illustrator in a way that the colors were defined via classes in a style block; error-prone and non-obvious when collaborating with others, so 1.5.0 came as a relief).

Here's the output of sassvg 1.5.0 for one of these icons:

```css
url(data:image/svg+xml;charset=UTF-8,%3Csvg%20version%3D%221.1%22%20id%3D%22Layer_1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20x%3D%220px%22%20y%3D%220px%22%20viewBox%3D%220%200%2032%2032%22%20enable-background%3D%22new%200%200%2032%2032%22%20xml%3Aspace%3D%22preserve%22%20style%3D%22%22%3E%20%3Ccircle%20fill%3D%22#5C96DB%22%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%2F%3E%20%3C%2Fsvg%3E); }
```

If you look closely, you can see that there's a `#` instead of a `%23`:

```
...circle%20fill%3D%22#5C96DB%22%20cx...
```

Chrome and Firefox don't care, but Internet Explorer doesn't know what to do and doesn't show the icon.

I currently use a function `sassvg-keep-colors()` which wraps `sassvg()` to replace the `#` afterwards, but this has slightly "hacky" feel to it:

```scss
@function _sassvgkeepcolors-str-replace($string, $search, $replace: '') {
  $index: str-index($string, $search);
  
  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + _sassvgkeepcolors-str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }
  
  @return $string;
}

@function sassvg-keep-colors($name) {
    $originalText: sassvg($name);
    $hashesReplaced: _sassvgkeepcolors-str-replace($originalText,'#','%23');
    @return $hashesReplaced;
}
```
